plugins {
    id 'net.neoforged.gradle.userdev' version '7.0.145'
}

version = project.mod_version
group   = project.maven_group
base { archivesName = project.archives_base_name }

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

dependencies {
    implementation "net.neoforged:neoforge:${project.neo_version}"
}
