plugins {
    id 'architectury-plugin'
    id 'dev.architectury.loom'
}

architectury { common() }

loom {
    accessWidenerPath = file('src/main/resources/rtbridge.accesswidener')
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
}
